import { useEffect, useState } from 'react';
import './styles.css';
import { api, logout } from './api';

type Screen='login'|'dashboard'|'topic'|'assessment'|'result'|'analysis'|'twin'|'recommendation'|'practice'|'progress';
const topics=['Factorization','Quadratic Equations'];

export default function App(){
 const [screen,setScreen]=useState<Screen>(localStorage.getItem('eduos_access_token')?'dashboard':'login');
 const [topic,setTopic]=useState('Factorization'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[answer,setAnswer]=useState('');
 const [loading,setLoading]=useState(false),[error,setError]=useState(''),[usingMock,setUsingMock]=useState(false);
 const [student,setStudent]=useState<any>(null),[twin,setTwin]=useState<any>(null),[attempt,setAttempt]=useState<any>(null),[question,setQuestion]=useState<any>(null),[result,setResult]=useState<any>(null),[analysis,setAnalysis]=useState<any>(null),[recommendation,setRecommendation]=useState<any>(null);

 async function run<T>(work:()=>Promise<T>,fallback:T|null=null):Promise<T|null>{
  setLoading(true);setError('');
  try{return await work()}catch(e){setError(e instanceof Error?e.message:'Something went wrong');if(fallback!==null){setUsingMock(true);return fallback}return null}finally{setLoading(false)}
 }
 useEffect(()=>{if(screen==='dashboard'&&localStorage.getItem('eduos_access_token')&&!localStorage.getItem('eduos_access_token')?.startsWith('demo-'))void run(async()=>{const [s,t]=await Promise.all([api.student(),api.twin()]);setStudent(s);setTwin(t);return true},true);else if(screen==='dashboard'&&localStorage.getItem('eduos_access_token')?.startsWith('demo-')){setStudent({display_name:'Demo Student'});setTwin({overall_mastery:68,confidence:76})}},[screen]);

 const signIn=async()=>{if(!email.trim()||!password){setError('Please enter your email and password.');return}const data=await run(()=>api.login(email.trim(),password));if(data){setUsingMock(false);setScreen('dashboard')}};
 const demoSignIn=()=>{localStorage.setItem('eduos_access_token','demo-token');setUsingMock(true);setError('');setStudent({display_name:'Demo Student'});setTwin({overall_mastery:68,confidence:76});setScreen('dashboard')};
 const startAssessment=async()=>{const assessments=await run(()=>api.assessments(),[]);const list=Array.isArray(assessments)?assessments:[];const selected=list.find((x:any)=>String(x?.name??x?.title??'').toLowerCase().includes(topic.toLowerCase()));if(selected?.id){const a=await run(()=>api.start(String(selected.id)));const qs=await run(()=>api.questions(String(selected.id)),[]);setAttempt(a);setQuestion(Array.isArray(qs)?qs[0]:null)}else{setUsingMock(true);setQuestion({id:'demo-q1',question_text:'Factorize the quadratic expression',question:'x² + 5x + 6'})}setScreen('assessment')};
 const normalizeAnswer=(value:string)=>value.toLowerCase().replace(/\s/g,'').replace(/[×·]/g,'*');
 const demoAnswerIsCorrect=()=>{const v=normalizeAnswer(answer);return v==='(x+2)(x+3)'||v==='(x+3)(x+2)'||v==='(x+2)*(x+3)'||v==='(x+3)*(x+2)'};
 const submitAnswer=async()=>{if(!attempt?.attempt_id||!question?.id){const correct=demoAnswerIsCorrect();setResult({score:correct?100:0,answer_id:correct?'demo-correct':'demo-wrong',is_correct:correct});setScreen('result');return}await run(()=>api.answer(String(attempt.attempt_id),{question_id:String(question.id),student_answer:answer,time_taken_seconds:0}));const r=await run(()=>api.submit(String(attempt.attempt_id)));setResult(r);setScreen('result')};
 const buildDemoAnalysis=()=>{const correct=result?.is_correct===true;return correct?{is_correct:true,concept:{name:topic},misconception:{title:'No major misconception detected',description:'Your answer matches the required factor pair.',confidence:.96}}:{is_correct:false,concept:{name:topic},misconception:{title:'Factor-pair selection misconception',description:`Your answer “${answer || 'No answer'}” does not produce x² + 5x + 6. The two numbers must multiply to 6 and add to 5, giving 2 and 3.`,confidence:.94},recommended_action:'Practice identifying factor pairs from product and sum.'}};
 const openAnalysis=async()=>{const id=result?.answer_id||result?.answers?.[0]?.id;if(id&&!String(id).startsWith('demo-')){const data=await run(()=>api.mindtrace(String(id)),null);setAnalysis(data||buildDemoAnalysis())}else setAnalysis(buildDemoAnalysis());setScreen('analysis')};
 const openTwin=()=>{setScreen('twin')};
 const openRecommendation=async()=>{const id=analysis?.concept_id||analysis?.concept?.id;if(id)setRecommendation(await run(()=>api.pathai(String(id))));else setRecommendation({action:'Targeted Factorization Practice',reason:'Strengthen factor-pair selection and sign patterns before reassessment.',duration_minutes:5});setScreen('recommendation')};
 const nav=(s:Screen)=>{setError('');setScreen(s)};
 const exit=()=>{logout();setUsingMock(false);setScreen('login')};

 return <main className="app">
  <header><div className="brand">Edu<span>OS</span></div>{screen!=='login'&&<nav><button className="ghost" onClick={()=>nav('dashboard')}>⌂ Dashboard</button><button className="ghost" onClick={()=>nav('progress')}>Progress</button><button className="ghost" onClick={exit}>Logout</button></nav>}</header>
  {loading&&<div className="loading">Connecting to EduOS…</div>}{error&&<div className="error">{error}{usingMock&&' Demo mode is available below.'}</div>}
  <section className="shell">
   {screen==='login'&&<div className="login-wrap">
    <div className="login-visual"><div className="orb orb-a"/><div className="orb orb-b"/><div className="visual-content"><div className="mini-logo">✦</div><p className="eyebrow light">EDUOS · SMART LEARNING</p><h1>Learn smarter.<br/><span>Understand deeper.</span></h1><p>AI-powered assessment that finds learning gaps, explains misconceptions and builds your next practice step.</p><div className="feature-row"><span>✓ Grade 10 Maths</span><span>✓ MindTrace AI</span><span>✓ EduTwin progress</span></div></div></div>
    <div className="login-card"><p className="eyebrow">WELCOME BACK</p><h2>Sign in to EduOS</h2><p className="muted">Continue your personalized learning journey.</p><form onSubmit={e=>{e.preventDefault();void signIn()}}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} placeholder="student@example.com" autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Enter your password" autoComplete="current-password"/></label><button className="primary wide" type="submit" disabled={loading}>Sign in <span>→</span></button></form><div className="divider"><span>or</span></div><button className="demo wide" onClick={demoSignIn} disabled={loading}>Continue with Demo <span>↗</span></button><small>Demo mode lets you present the full student flow without a running backend.</small></div>
   </div>}
   {screen==='dashboard'&&<><div className="page-head"><div><p className="eyebrow">STUDENT DASHBOARD</p><h1>Good morning{student?.display_name?', '+student.display_name:''} 👋</h1><p className="muted">Your learning journey, all in one place.</p></div><button className="primary" onClick={()=>nav('topic')}>Start SmartAssess <span>→</span></button></div><div className="stats"><div className="stat-card"><div className="stat-icon purple">◔</div><span>Overall mastery</span><strong>{twin?.overall_mastery??twin?.mastery??68}%</strong><div className="bar"><i style={{width:String(Number(twin?.overall_mastery??twin?.mastery??68))+'%'}}/></div></div><div className="stat-card"><div className="stat-icon green">↗</div><span>Confidence</span><strong>{twin?.confidence??76}%</strong><p className="muted">Keep building consistency.</p></div><div className="stat-card"><div className="stat-icon orange">◎</div><span>Current focus</span><strong>Factorization</strong><p className="muted">Recommended by EduTwin.</p></div></div><div className="section-title"><h2>Learning cycle</h2><span>AI-guided</span></div><div className="cycle">{[['01','SmartAssess','Check what you know'],['02','MindTrace','Understand the gap'],['03','PathAI','Practice the right skill'],['04','EduTwin','Track your growth']].map(([n,t,d])=><div className="cycle-card" key={n}><b>{n}</b><h3>{t}</h3><p>{d}</p></div>)}</div></>}
   {screen==='topic'&&<><p className="eyebrow">SMARTASSESS · GRADE 10</p><h1>Choose your focus</h1><p className="muted">Select a mathematics topic to begin an adaptive assessment.</p><div className="topic-grid">{topics.map((t,i)=><button className={'topic-card '+(topic===t?'selected':'')} onClick={()=>setTopic(t)} key={t}><span className="topic-number">0{i+1}</span><div><b>{t}</b><span>Adaptive assessment</span></div><em>→</em></button>)}</div><button className="primary" onClick={startAssessment} disabled={loading}>Begin {topic} Assessment <span>→</span></button></>}
   {screen==='assessment'&&<><div className="assessment-top"><div><p className="eyebrow">SMARTASSESS · {topic}</p><h1>Let's solve this together.</h1></div><span className="question-count">Question 1 / 5</span></div><div className="progress-line"><i/></div><div className="question-card"><span className="tag">MATHEMATICS</span><p>{question?.question_text??question?.text??'Factorize the quadratic expression'}</p><h2>{question?.question??'x² + 5x + 6'}</h2><label>Your answer<input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="e.g. (x + 2)(x + 3)" autoFocus/></label><button className="primary" onClick={submitAnswer} disabled={loading||!answer.trim()}>Submit answer <span>→</span></button></div></>}
   {screen==='result'&&<div className="center-page"><div className="success-icon">✓</div><p className="eyebrow">ASSESSMENT COMPLETE</p><h1>Nice work!</h1><p className="muted">Your response is ready for AI analysis.</p><div className="result-score"><span>Score</span><strong>{result?.score!=null?result.score:'—'}</strong></div><button className="primary" onClick={openAnalysis} disabled={loading}>View MindTrace analysis <span>→</span></button></div>}
   {screen==='analysis'&&<><p className="eyebrow">MINDTRACE AI</p><h1>Understand your answer</h1><p className="muted">A clear explanation of what happened and why.</p><div className="analysis-grid"><div className="analysis-main card"><div className="analysis-status">{analysis?.is_correct===true?'✓ Correct response':'! Needs review'}</div><h2>{analysis?.misconception?.title??'No major misconception detected'}</h2><p>{analysis?.misconception?.description??'Keep practicing the concept with varied examples.'}</p></div><div className="card confidence-card"><span>AI confidence</span><strong>{Math.round(Number(analysis?.misconception?.confidence??.8)*100)}%</strong><div className="confidence-ring"><b>{Math.round(Number(analysis?.misconception?.confidence??.8)*100)}%</b></div></div></div><button className="primary" onClick={openTwin}>Update my EduTwin <span>→</span></button></>}
   {screen==='twin'&&<><p className="eyebrow">EDUTWIN · LEARNING STATE</p><h1>Your learning state was updated.</h1><p className="muted">MindTrace has added this result to your learning profile. PathAI will use it to choose the next learning action.</p><div className="twin-update"><div className="update-row"><span>Concept</span><strong>{topic}</strong></div><div className="update-row"><span>Mastery</span><strong>{twin?.overall_mastery??68}% <small>current estimate</small></strong></div><div className="update-row"><span>Confidence</span><strong>{twin?.confidence??76}%</strong></div><div className="update-row"><span>Learning signal</span><strong>{analysis?.is_correct===true?'Strengthening':'Needs targeted practice'}</strong></div></div><button className="primary" onClick={openRecommendation} disabled={loading}>Get PathAI next step <span>→</span></button></>}
   {screen==='recommendation'&&<><p className="eyebrow">PATHAI · PERSONALIZED PLAN</p><h1>Your next step</h1><p className="muted">One focused activity before you reassess.</p><div className="recommend-card"><div className="path-icon">✦</div><div><span className="tag">RECOMMENDED</span><h2>{recommendation?.action??'Targeted Factorization Practice'}</h2><p>{recommendation?.reason??'Practice the identified concept before reassessment.'}</p><span className="pill">⏱ {recommendation?.duration_minutes??5} min</span></div></div><button className="primary" onClick={()=>nav('practice')}>Start practice <span>→</span></button></>}
   {screen==='practice'&&<><p className="eyebrow">TARGETED PRACTICE</p><h1>Build the concept</h1><p className="muted">Quick practice · Factorization</p><div className="practice-card"><span className="tag">QUESTION 1</span><h2>Which pair of integers multiplies to <b>6</b> and adds to <b>5</b>?</h2><div className="answers"><button onClick={()=>nav('progress')}>2 and 3</button><button onClick={()=>nav('progress')}>1 and 6</button></div></div></>}
   {screen==='progress'&&<><p className="eyebrow">EDUTWIN · LEARNING PROFILE</p><h1>Your progress</h1><p className="muted">A simple view of your current learning state.</p><div className="twin-grid"><div className="twin-card big"><span>Mastery</span><strong>{twin?.overall_mastery??twin?.mastery??68}%</strong><div className="bar"><i style={{width:String(Number(twin?.overall_mastery??twin?.mastery??68))+'%'}}/></div></div><div className="twin-card"><span>Confidence</span><strong>{twin?.confidence??76}%</strong></div><div className="twin-card"><span>Misconception</span><strong>{analysis?.misconception?.title??'None detected'}</strong></div><div className="twin-card"><span>Recommended action</span><strong>{recommendation?.action??'Reassess Factorization'}</strong></div></div><button className="primary" onClick={()=>nav('topic')}>Reassess Factorization <span>→</span></button></>}
  </section>
 </main>;
}