import { useState } from 'react';
import './styles.css';

type Screen='login'|'dashboard'|'topic'|'assessment'|'result'|'analysis'|'recommendation'|'practice'|'progress';
const topics=['Factorization','Quadratic Equations'];
export default function App(){const [screen,setScreen]=useState<Screen>('login'); const [topic,setTopic]=useState('Factorization'); const [answer,setAnswer]=useState(''); const [submitted,setSubmitted]=useState(false);
const nav=(s:Screen)=>{setScreen(s);setSubmitted(false)};
return <main className="app"><header><div className="brand">Edu<span>OS</span></div>{screen!=='login'&&<button className="ghost" onClick={()=>nav('dashboard')}>Dashboard</button>}</header>
<section className="shell">{screen==='login'&&<div className="card hero"><p className="eyebrow">AI-powered learning platform</p><h1>Learn smarter.<br/>Understand deeper.</h1><p className="muted">Personalized assessment, misconception analysis and targeted practice for Grade 10 Mathematics.</p><button onClick={()=>nav('dashboard')}>Continue as Student →</button></div>}
{screen==='dashboard'&&<><p className="eyebrow">STUDENT DASHBOARD</p><h1>Good morning 👋</h1><div className="grid"><div className="card"><span>Overall mastery</span><strong>68%</strong><div className="bar"><i style={{width:'68%'}}/></div></div><div className="card"><span>Current focus</span><strong>Factorization</strong><p className="muted">Mastery 41% · Needs practice</p></div></div><button onClick={()=>nav('topic')}>Start SmartAssess →</button></>}
{screen==='topic'&&<><p className="eyebrow">MATHEMATICS · GRADE 10</p><h1>Choose a topic</h1><div className="grid">{topics.map(t=><button className={'topic '+(topic===t?'selected':'')} onClick={()=>setTopic(t)} key={t}><b>{t}</b><span>Adaptive assessment</span></button>)}</div><button onClick={()=>nav('assessment')}>Begin {topic} Assessment →</button></>}
{screen==='assessment'&&<><p className="eyebrow">SMARTASSESS · {topic}</p><h1>Question 1</h1><div className="card question"><p>Factorize</p><h2>x² + 5x + 6</h2><input value={answer} onChange={e=>setAnswer(e.target.value)} placeholder="Enter your answer"/><button onClick={()=>{setSubmitted(true);nav('result')}}>Submit Answer</button></div></>}
{screen==='result'&&<><p className="eyebrow">ASSESSMENT RESULT</p><h1>Answer submitted</h1><div className="card"><strong>{submitted?'Analysis ready':'Analysis ready'}</strong><p className="muted">Your response has been processed by the learning engine.</p><button onClick={()=>nav('analysis')}>View AI Analysis →</button></div></>}
{screen==='analysis'&&<><p className="eyebrow">MINDTRACE</p><h1>Understand your mistake</h1><div className="card"><label>Result</label><h2>Needs review</h2><label>Misconception</label><p>Difficulty identifying factor pairs that multiply to the constant term.</p><label>Root cause</label><p>Sign and product relationship needs reinforcement.</p><label>Evidence</label><p>Your submitted expression did not match the required factor pair.</p><label>Confidence</label><div className="confidence">80%</div></div><button onClick={()=>nav('recommendation')}>See Learning Recommendation →</button></>}
{screen==='recommendation'&&<><p className="eyebrow">PATHAI</p><h1>Your next step</h1><div className="card"><h2>Targeted Factorization Practice</h2><p className="muted">Practice factor pairs before attempting another assessment.</p><div className="pill">5 questions · 5 min</div></div><button onClick={()=>nav('practice')}>Start Practice →</button></>}
{screen==='practice'&&<><p className="eyebrow">TARGETED PRACTICE</p><h1>Build the concept</h1><div className="card"><p>Which pair of integers multiplies to <b>6</b> and adds to <b>5</b>?</p><div className="answers"><button onClick={()=>nav('progress')}>2 and 3</button><button onClick={()=>nav('progress')}>1 and 6</button></div></div></>}
{screen==='progress'&&<><p className="eyebrow">EDUTWIN · PROGRESS</p><h1>Your learning twin</h1><div className="grid"><div className="card"><span>Mastery</span><strong>72%</strong></div><div className="card"><span>Confidence</span><strong>76%</strong></div><div className="card"><span>Misconception</span><strong>Factor pairs</strong></div><div className="card"><span>Recommended action</span><strong>Reassess Factorization</strong></div></div><button onClick={()=>nav('assessment')}>Reassess →</button></>}
</section></main>}
