import{useEffect,useState}from'react';import'./styles.css';import{api}from'./api';import{useAuth,type Role}from'./AuthContext';import{ProtectedRoute,roleDashboard}from'./ProtectedRoute';
type Screen='dashboard'|'topic'|'assessment'|'result'|'analysis'|'progress';
const topics=['Factorization','Quadratic Equations'];
function pathScreen(){const p=window.location.pathname;if(p.endsWith('/dashboard'))return'dashboard';if(p.includes('/assessment'))return'assessment';return'dashboard';}
function RoleHome({role}:{role:Role}){const{applicationUser,logout}=useAuth();return <main className="shell"><p className="eyebrow">EDUOS · {role}</p><h1>{role[0]+role.slice(1).toLowerCase()} Dashboard</h1><p className="muted">Signed in as {applicationUser?.email}. Your application role is resolved from the trusted user record.</p><div className="card" style={{marginTop:24}}><h2>Dashboard ready</h2><p className="muted">Role-based access is active. Educational modules can now be connected to this protected surface without trusting browser-supplied roles.</p><button className="primary" onClick={()=>void logout().then(()=>{window.history.replaceState({},'','/login');window.location.reload()})}>Sign out</button></div></main>}
function StudentApp(){const{applicationUser,logout}=useAuth();const[screen,setScreen]=useState<Screen>(pathScreen());const[email,setEmail]=useState('');const[student,setStudent]=useState<any>(null);const[twin,setTwin]=useState<any>(null);const[topic,setTopic]=useState(topics[0]);const[question,setQuestion]=useState<any>(null);const[attempt,setAttempt]=useState<any>(null);const[answer,setAnswer]=useState('');const[result,setResult]=useState<any>(null);const[analysis,setAnalysis]=useState<any>(null);const[error,setError]=useState('');const[loading,setLoading]=useState(false);
const nav=(next:Screen,path='/student/dashboard')=>{setError('');setScreen(next);window.history.pushState({},'',path)};useEffect(()=>{const onPop=()=>setScreen(pathScreen());window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop)},[]);
useEffect(()=>{if(applicationUser?.role!=='STUDENT')return;void(async()=>{try{const[s,t]=await Promise.all([api.student(),api.twin()]);setStudent(s);setTwin(t)}catch(e){setError(e instanceof Error?e.message:'Unable to load student data')}})()},[applicationUser?.role]);
const run=async<T>(fn:()=>Promise<T>)=>{setLoading(true);setError('');try{return await fn()}catch(e){setError(e instanceof Error?e.message:'Request failed');return null}finally{setLoading(false)}};
const start=async()=>{const list=await run(()=>api.assessments());if(!list)return;const selected=(list as any[]).find(x=>String(x.title??'').toLowerCase().includes(topic.toLowerCase()))??(list as any[])[0];if(!selected){setError('No published assessment is available.');return}const a=await run(()=>api.start(String(selected.id)));if(!a)return;const qs=await run(()=>api.questions(String(selected.id)));if(!qs||!(qs as any[])[0])return;setAttempt(a);setQuestion((qs as any[])[0]);nav('assessment','/student/assessment')};
const submit=async()=>{if(!attempt||!question||!answer.trim())return;const saved=await run(()=>api.answer(String(attempt.attempt_id),{question_id:String(question.id),student_answer:answer,time_taken_seconds:0}));if(!saved)return;const r=await run(()=>api.submit(String(attempt.attempt_id)));if(r){setResult({...r,answer_id:(saved as any).answer_id});nav('result','/student/result')}};
const analyze=async()=>{if(!result?.answer_id)return;const a=await run(()=>api.mindtrace(String(result.answer_id)));if(a){setAnalysis(a);nav('analysis','/student/analysis')}};
return <><header className="topbar"><div className="brand">Edu<span>OS</span></div><div className="topbar-center">Grade 10 Mathematics</div><button className="ghost" onClick={()=>void logout().then(()=>{window.history.replaceState({},'','/login');window.location.reload()})}>Sign out</button></header>{error&&<div className="error">{error}</div>}<main className="shell">{loading&&<div className="loading">Working…</div>}
{screen==='dashboard'&&<><p className="eyebrow">STUDENT DASHBOARD</p><h1>Let's continue building your Mathematics mastery.</h1><div className="reference-stats"><div className="reference-stat"><span>Overall Mastery</span><strong>{twin?.overall_mastery??0}%</strong></div><div className="reference-stat"><span>Student</span><strong>{student?.display_name??applicationUser?.display_name??'Student'}</strong></div><div className="reference-stat"><span>Role</span><strong>{applicationUser?.role}</strong></div><div className="reference-stat"><span>Learning focus</span><strong>Quadratics</strong></div></div><div className="daily-plan"><p className="eyebrow">YOUR DAILY PLAN</p><h2>Today's Learning Path</h2><button className="primary dashboard-cta" onClick={()=>nav('topic','/student/assessment')}>Start SmartAssess →</button></div></>}
{screen==='topic'&&<><p className="eyebrow">SMARTASSESS · GRADE 10</p><h1>Choose your focus</h1><p className="muted">Select a mathematics topic to begin an adaptive assessment.</p><div className="topic-grid">{topics.map(t=><button className={'topic-card '+(topic===t?'selected':'')} key={t} onClick={()=>setTopic(t)}><div><b>{t}</b><span>Adaptive assessment</span></div><em>→</em></button>)}</div><button className="primary" onClick={()=>void start()}>Begin {topic} Assessment →</button></>}
{screen==='assessment'&&<><p className="eyebrow">SMARTASSESS · {topic}</p><h1>Let's solve this together.</h1><div className="question-card"><span className="tag">MATHEMATICS</span><p>{question?.question_text??'Question'}</p><h2>{question?.question??question?.text??''}</h2><label>Your answer<input value={answer} onChange={e=>setAnswer(e.target.value)} autoFocus/></label><button className="primary" onClick={()=>void submit()}>Submit answer →</button></div></>}
{screen==='result'&&<div className="center-page"><div className="success-icon">✓</div><p className="eyebrow">ASSESSMENT COMPLETE</p><h1>Nice work!</h1><div className="result-score"><span>Score</span><strong>{result?.score??'—'}</strong></div><button className="primary" onClick={()=>void analyze()}>View MindTrace analysis →</button></div>}
{screen==='analysis'&&<><p className="eyebrow">MINDTRACE AI</p><h1>Understand your answer</h1><div className="card"><h2>{analysis?.misconception?.title??'Analysis complete'}</h2><p className="muted">{analysis?.misconception?.description??'No additional explanation was returned.'}</p></div><button className="primary" onClick={()=>nav('progress','/student/dashboard')}>Back to dashboard →</button></>}
{screen==='progress'&&<><p className="eyebrow">EDUTWIN</p><h1>Your progress</h1><div className="twin-grid"><div className="twin-card big"><span>Mastery</span><strong>{twin?.overall_mastery??0}%</strong></div></div></>}
</main></>}
function App(){const{loading,authenticated,role,error}=useAuth();if(loading)return <div className="auth-loading">Restoring secure session…</div>;const path=window.location.pathname;if(!authenticated){if(path!=='/login')window.history.replaceState({},'','/login');return <Login/>}if(path==='/'||path==='/login'){window.history.replaceState({},'',roleDashboard(role));window.location.reload();return null}if(role==='STUDENT')return <ProtectedRoute allowedRoles={['STUDENT']}><StudentApp/></ProtectedRoute>;return <ProtectedRoute allowedRoles={[role as Role]}><RoleHome role={role as Role}/></ProtectedRoute>}
function Login(){const{login,error:authError}=useAuth();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[busy,setBusy]=useState(false);const[localError,setLocalError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();setLocalError('');if(!email||!password){setLocalError('Enter email and password.');return}setBusy(true);try{await login(email,password)}catch{}finally{setBusy(false)}};return <main className="login-wrap"><div className="login-visual"><div className="visual-content"><div className="mini-logo">✦</div><p className="eyebrow light">EDUOS · SMART LEARNING</p><h1>Learn smarter.<br/><span>Understand deeper.</span></h1><p>AI-powered assessment, learning insights and role-specific dashboards.</p></div></div><div className="login-card"><p className="eyebrow">WELCOME BACK</p><h2>Sign in to EduOS</h2><p className="muted">Authentication is secured by Supabase.</p><form onSubmit={submit}><label>Email<input value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label><button className="primary wide" disabled={busy}>Sign in →</button></form>{(localError||authError)&&<div className="error">{localError||authError}</div>}</div></main>}
export default App;
